channels:
- conda-forge
dependencies:
- breathe
- catch2
- cmake
- doxygen
- eigen
- gmatelastic
- gmatelastoplasticqpot
- mathjax
- ninja
- numpy
- pybind11
- python
- scikit-build
- setuptools_scm
- sphinx
- sphinx-tabs
- sphinx_rtd_theme
- xsimd
- xtensor
- xtensor-python
